/*
 * Copyright (C) 2026 Yukthi Systems Private Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * version 3 along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

import { CircleChevronLeft, KeyRound } from "lucide-react";
import { useState } from "react";
import OTPInput from "react-otp-input";
import { useBackupLogin } from "@/hooks/useTFA";
import { useToastify } from "@/hooks/useToastify";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useSetAtom } from "jotai";
import { itemsAtom } from "@/store/tfaMethods";

function BackupLogin() {
  const location = useLocation();
  const redirectPath = location.state?.redirectPath || "/";
  const [backup, setBackup] = useState("");
  const { mutate, isPending } = useBackupLogin();
  const navigate = useNavigate();
  const toast = useToastify();
  const setItems = useSetAtom(itemsAtom);

  const handleVerifyClick = async () => {
    let UpperCase = backup.toUpperCase();
    if (backup.length === 6) {
      let queryParams = {
        code: UpperCase,
      };

      mutate(
        { queryParams },
        {
          onSuccess: () => {
            toast("success", "Backup code verification successful.");
            setItems([]);
            sessionStorage.removeItem("redirectAfterLogin");

            // Navigate after successful verification
            navigate(redirectPath, { replace: true });
          },
          onError: (error) => {
            console.error(
              error.message || "Backup code verification failed...!",
            );
            const message =
              error.response?.data?.message || error.message || "Unknown error";
            const tracebackId = error.response?.data?.traceback_id;
            toast(
              "error",
              `Message: ${message}${tracebackId ? `\nTraceback ID: ${tracebackId}` : ""}`,
            );
            setItems([]);
            navigate("/login");
          },
        },
      );
    }
  };

  function handleBack() {
    navigate(-1);
  }

  return (
    <div className="w-full h-screen flex justify-center items-center">
      <div className="min-w-4/12 bg-card p-5 shadow-lg rounded-xl">
        <div className="w-full grid grid-col-3">
          <div>
            <span className="text-primary cursor-pointer" onClick={handleBack}>
              <CircleChevronLeft />
            </span>
          </div>
          <div>
            <div className="mx-auto mb-3 w-20 h-20 bg-primary/20 rounded-full flex justify-center items-center text-primary">
              <KeyRound size={45} />
            </div>
          </div>
          <div></div>
        </div>
        <h2 className="m-2 text-2xl font-semibold text-center">
          Backup Code Authentication
        </h2>
        <h2 className="mx-auto w-8/12 text-center text-lg my-4">
          Please enter the 6-digit code generated by your backup method.
        </h2>

        <div className="flex justify-center my-6">
          <OTPInput
            value={backup}
            onChange={setBackup}
            numInputs={6}
            isInputNum
            shouldAutoFocus
            renderInput={(props) => <input {...props} />}
            inputStyle={{
              width: "3rem",
              height: "3rem",
              margin: "0 0.5rem",
              fontSize: "1.5rem",
              fontWeight: "bold",
              borderRadius: "8px",
              border: "1px solid #ccc",
              outlineColor: "#8169c9",
              textTransform: "uppercase",
            }}
          />
        </div>
        <button
          onClick={handleVerifyClick}
          disabled={backup.length !== 6 || isPending}
          className="bg-primary/90 w-6/12 text-white px-4 py-2 rounded-lg cursor-pointer hover:bg-primary disabled:opacity-50 font-medium mx-auto block"
        >
          {isPending ? "Verifying..." : "Verify Backup Code"}
        </button>
        <div className="mt-4 text-center text-sm text-gray-500">
          <p>
            If you don't have Backup codes, Click{" "}
            <Link
              to={`/2fa/select-method`}
              state={{ redirectPath }}
              className="text-blue-500 hover:underline"
            >
              here
            </Link>{" "}
            to Select 2FA Method.
          </p>
        </div>
      </div>
    </div>
  );
}

export default BackupLogin;
