/*
 * Copyright (C) 2026 Yukthi Systems Private Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * version 3 along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

import { CircleChevronLeft, ShieldEllipsis } from "lucide-react";
import { useEffect, useState } from "react";
import OTPInput from "react-otp-input";
import {
  useSendEmailOTP,
  useSendPhoneOTP,
  useValidateEmailAuthOTP,
  useValidatePhoneAuthOTP,
  useValidateTFA,
} from "@/hooks/useTFA";
import { useToastify } from "@/hooks/useToastify";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import ResendButtonWithTimer from "@/components/common/ResendButtonWithTimer";
import { itemsAtom } from "@/store/tfaMethods";
import { useSetAtom } from "jotai";
import { addLogs } from "@/api/logs";

const methodConfigs = {
  email: {
    label: "Email",
    message: "sent to your email.",
  },
  sms: {
    label: "SMS",
    message: "sent to your mobile.",
  },
  totp: {
    label: "Authenticator App",
    message: "generated by your Authenticator app.",
  },
};

function Totp() {
  const setItems = useSetAtom(itemsAtom);
  const location = useLocation();
  const user = location.state?.user || "";
  const redirectPath = location.state?.redirectPath || "/";
  const [otp, setOtp] = useState("");
  const toast = useToastify();
  const navigate = useNavigate();
  const { method } = useParams();

  const { mutate: validateTFA, isPending } = useValidateTFA();
  const { mutate: sendEmailOTP } = useSendEmailOTP();
  const { mutate: validateEmailOTP } = useValidateEmailAuthOTP();
  const { mutate: sendSMSOTP } = useSendPhoneOTP();
  const { mutate: validateSMSOTP } = useValidatePhoneAuthOTP();

  const showToastError = (error, fallbackMessage) => {
    const message =
      error?.response?.data?.message || error?.message || fallbackMessage;
    const tracebackId = error?.response?.data?.traceback_id;
    toast(
      "error",
      `Message: ${message}${tracebackId ? `\nTraceback ID: ${tracebackId}` : ""}`,
    );
  };

  const handleVerifyClick = () => {
    let UpperCase = otp.toUpperCase();
    if (otp.length !== 6 || !method) return;

    const queryParams =
      method === "totp" ? { totp_code: UpperCase } : { otp_code: UpperCase };

    const onSuccess = async (response) => {
      toast(
        "success",
        `${methodConfigs[method]?.label || "2FA"} verification successful.`,
      );

      await addLogs({
        values: {
          message: "Login successful",
        },
        type: "success",
        method: "POST",
        action_type: "user_login",
        payload: { user_name: user },
        message: `User ${user} successfully authenticated and logged in`,
        user: user,
      });

      setItems([]);

      // Clear stored redirect path and navigate
      sessionStorage.removeItem("redirectAfterLogin");
      navigate(redirectPath, { replace: true });
    };

    const onError = async (error) => {
      showToastError(
        error,
        `${methodConfigs[method]?.label || "2FA"} verification failed.`,
      );

      await addLogs({
        values: error,
        type: "error",
        method,
        action_type: "user_login",
        payload: { user_name: user },
        message: `Login attempt failed for user ${user}`,
        user: user,
      });

      setItems([]);
      navigate("/login");
    };

    if (method === "totp") {
      validateTFA({ queryParams }, { onSuccess, onError });
    } else if (method === "email") {
      validateEmailOTP({ queryParams }, { onSuccess, onError });
    } else if (method === "sms") {
      validateSMSOTP({ queryParams }, { onSuccess, onError });
    }
  };

  const resendOTP = () => {
    const onSuccess = () =>
      toast(
        "success",
        `${methodConfigs[method]?.label} OTP sent successfully.`,
      );

    const onError = (error) =>
      showToastError(
        error,
        `Failed to send ${methodConfigs[method]?.label} OTP.`,
      );

    if (method === "email") sendEmailOTP(null, { onSuccess, onError });
    else if (method === "sms") sendSMSOTP(null, { onSuccess, onError });
  };

  useEffect(() => {
    if (method === "email" || method === "sms") {
      resendOTP();
    }
  }, [method]);

  function handleBack() {
    navigate(-1);
  }

  return (
    <div className="w-full h-screen flex justify-center items-center">
      <div className="min-w-4/12 bg-card p-6 shadow-lg rounded-xl">
        <div className="w-full grid grid-col-3">
          <div>
            <span className="text-primary cursor-pointer" onClick={handleBack}>
              <CircleChevronLeft />
            </span>
          </div>
          <div>
            <div className="mx-auto mb-3 w-20 h-20 bg-primary/20 rounded-full flex justify-center items-center text-primary">
              <ShieldEllipsis size={45} />
            </div>
          </div>
          <div></div>
        </div>
        <h2 className="text-2xl font-semibold text-center">
          Two-Factor Authentication
        </h2>
        <p className="mx-auto text-center text-lg my-4 w-10/12">
          Please enter the 6-digit code{" "}
          {methodConfigs[method]?.message || "sent to your device."}
        </p>

        <div className="flex justify-center my-6">
          <OTPInput
            value={otp}
            onChange={setOtp}
            numInputs={6}
            isInputNum
            shouldAutoFocus
            renderInput={(props) => <input {...props} />}
            inputStyle={{
              width: "3rem",
              height: "3rem",
              margin: "0 0.5rem",
              fontSize: "1.5rem",
              fontWeight: "bold",
              borderRadius: "8px",
              border: "1px solid #ccc",
              outlineColor: "#8169c9",
              textTransform: "uppercase",
            }}
          />
        </div>

        <button
          onClick={handleVerifyClick}
          disabled={otp.length !== 6 || isPending}
          className="bg-primary/90 w-6/12 text-white px-4 py-2 rounded-lg hover:bg-primary transition disabled:opacity-50 font-medium mx-auto block"
        >
          {isPending
            ? "Verifying..."
            : `Verify ${methodConfigs[method]?.label || "OTP"}`}
        </button>

        {method !== "totp" && (
          <div className="flex justify-between mt-3 w-6/12 mx-auto">
            <button
              className="py-1 px-2 text-gray-600 rounded"
              onClick={() => navigate(-1)}
            >
              Back
            </button>
            <ResendButtonWithTimer onResend={resendOTP} initialTimer={120} />
          </div>
        )}

        <div className="mt-4 text-center text-sm text-gray-500">
          <p>
            Lost access to your Authenticator app?{" "}
            <Link
              to="/2fa/backup-code-login"
              state={{ redirectPath }}
              className="text-blue-500 hover:underline"
            >
              Login with backup code
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}

export default Totp;
