/*
 * Copyright (C) 2026 Yukthi Systems Private Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * version 3 along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

import React, { useEffect, useRef } from "react";
import { Input } from "@/components/common/Inputs";
import { Switch } from "@/components/common/Switch";
import PhoneInput from "@/components/common/PhoneInput";

function IdentityDetailsStep({ register, errors, control, watch, setValue, domain_name, isEdit }) {
  const firstName = watch("first_name") || "";
  const emailPrefix = watch("email_prefix") || "";
  const isEmailTwoFAEnabled = watch("is_email_2fa_enabled");

  // Auto-population logic
  const isManuallyEditedRef = useRef(false);
  const lastAutoValueRef = useRef("");

  useEffect(() => {
    if (isEdit) return;

    const sanitize = (val) =>
      val
        .toLowerCase()
        .replace(/\s+/g, ".")
        .replace(/[^a-z0-9._%+-]/g, "") || "";

    const autoGenerated = sanitize(firstName);

    if (
      firstName &&
      !isManuallyEditedRef.current &&
      (emailPrefix === lastAutoValueRef.current || !emailPrefix)
    ) {
      setValue("email_prefix", autoGenerated, { shouldValidate: true });
      lastAutoValueRef.current = autoGenerated;
    }
  }, [firstName, setValue, isEdit, emailPrefix]);

  const handleEmailChange = (e) => {
    const value = e.target.value.toLowerCase();
    setValue("email_prefix", value);

    const sanitize = (val) =>
      val
        .toLowerCase()
        .replace(/\s+/g, ".")
        .replace(/[^a-z0-9._%+-]/g, "") || "";
    const autoGenerated = sanitize(firstName);

    if (value !== autoGenerated) {
      isManuallyEditedRef.current = true;
    } else {
      isManuallyEditedRef.current = false;
      lastAutoValueRef.current = value;
    }
  };

  return (
    <div className="space-y-6">
      <div className="text-left">
        <h3 className="text-foreground text-lg font-semibold">
          Identity Information
        </h3>
        <p className="text-muted-foreground mt-1 text-sm">
          Set the personal details and email address for this E-Mail Identity
        </p>
      </div>

      <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* First Name */}
        <Input
          label="First Name"
          name="first_name"
          register={register}
          errors={errors}
          placeholder="John"
          isRequired={true}
        />

        {/* Last Name */}
        <Input
          label="Last Name"
          name="last_name"
          register={register}
          errors={errors}
          placeholder="Doe"
        />

        {/* Email Input - Minimal & Professional */}
        <div className="md:col-span-1">
          <label className="text-card-foreground block text-left text-sm font-medium">
            Email Address
            <span className="text-red-500"> *</span>
          </label>

          {/* Email Input Group */}
          <div className="relative mt-1">
            <input
              type="text"
              placeholder="prefix"
              maxLength={64}
              disabled={isEdit}
              {...register("email_prefix", {
                required: "Email prefix is required",
                onChange: handleEmailChange,
                validate: {
                  validChars: (value) =>
                    /^[a-zA-Z0-9._-]+$/.test(value) ||
                    "Only letters, numbers, dot, underscore, and hyphen are allowed",
                  noEdgeOrRepeatSymbols: (value) =>
                    /^[a-zA-Z0-9]+(?:[._-][a-zA-Z0-9]+)*$/.test(value) ||
                    "Symbols (. _ -) can't be at the start/end or appear consecutively",
                },
              })}
              className={`border border-border bg-card text-card-foreground placeholder:text-muted-foreground focus:border-primary focus:ring-primary w-full rounded-md p-2 pr-32 lowercase focus:outline-none disabled:cursor-not-allowed disabled:opacity-50 ${isEdit ? "bg-muted" : ""}`}
            />
            <div className="pointer-events-none absolute top-0 right-0 flex h-full items-center pr-3">
              <span className="text-muted-foreground">@{domain_name}</span>
            </div>
          </div>

          {/* Error Message */}
          {errors.email_prefix && (
            <p className="mt-1.5 text-left text-sm text-red-500">
              {errors.email_prefix.message}
            </p>
          )}

          {/* Email Preview - Clean & Minimal */}
          {emailPrefix && !errors.email_prefix && (
            <p className="text-muted-foreground mt-2 overflow-hidden text-left text-sm text-ellipsis whitespace-nowrap">
              Complete email:{" "}
              <span className="text-foreground font-medium">
                {emailPrefix}@{domain_name}
              </span>
            </p>
          )}
        </div>

        {/* Phone Number */}
        <PhoneInput
          label="Primary Phone Number"
          name="primary_phone_number"
          placeholder="1234567890"
          register={register}
          errors={errors}
          watch={watch}
          setValue={setValue}
          isRequired={true}
      
        />

        {/* Secondary Email */}
        <Input
          label="Recovery / Secondary Email"
          name="secondary_email"
          register={register}
          errors={errors}
          placeholder="recovery@example.com"
          isRequired={isEmailTwoFAEnabled}
          info={isEmailTwoFAEnabled ? "Mandatory since Email 2FA is enabled" : "Required to enable Email 2FA"}
        />

        {/* Identity Status Switch (moved to first step) */}
        <div className="md:col-span-2 border-t border-border pt-6 text-left">
          <h4 className="text-sm font-semibold text-foreground mb-4">Identity Status</h4>
          <Switch
            control={control}
            name="is_enabled"
            register={register}
            watch={watch}
            errors={errors}
            falseLabel="Disabled"
            falseSublabel="User will not be able to log in or use services"
            trueLabel="Enabled"
            trueSublabel="Identity is active and functional"
          />
        </div>
      </div>
    </div>
  );
}

export default IdentityDetailsStep;
